export const brands = [
  { id: 1, name: "Audi" },
  { id: 2, name: "BMW" },
  { id: 3, name: "Mercedes-Benz" },
  { id: 4, name: "Volkswagen" },
  { id: 5, name: "Toyota" },
  { id: 6, name: "Honda" },
  { id: 7, name: "Ford" },
  { id: 8, name: "Renault" },
  { id: 9, name: "Peugeot" },
  { id: 10, name: "Citroën" },
  { id: 11, name: "Seat" },
  { id: 12, name: "Skoda" },
  { id: 13, name: "Hyundai" },
  { id: 14, name: "Kia" },
  { id: 15, name: "Nissan" },
  { id: 16, name: "Mazda" },
  { id: 17, name: "Volvo" },
  { id: 18, name: "Tesla" },
  { id: 19, name: "Dacia" },
  { id: 20, name: "Jeep" },
];

export const models = [
  { id: 1, brandId: 1, name: "A3" },
  { id: 2, brandId: 1, name: "A4" },
  { id: 3, brandId: 2, name: "Serie 1" },
  { id: 4, brandId: 2, name: "Serie 3" },
  { id: 5, brandId: 3, name: "Clase A" },
  { id: 6, brandId: 3, name: "Clase C" },
  { id: 7, brandId: 4, name: "Golf" },
  { id: 8, brandId: 4, name: "Passat" },
  { id: 9, brandId: 5, name: "Corolla" },
  { id: 10, brandId: 5, name: "Yaris" },
  { id: 11, brandId: 7, name: "Focus" },
  { id: 12, brandId: 7, name: "Fiesta" },
  { id: 13, brandId: 8, name: "Clio" },
  { id: 14, brandId: 8, name: "Megane" },
  { id: 15, brandId: 11, name: "Ibiza" },
  { id: 16, brandId: 11, name: "Leon" },
];

export const insurances = [
  { id: 1, name: "Mapfre" },
  { id: 2, name: "Allianz" },
  { id: 3, name: "AXA" },
  { id: 4, name: "Mutua Madrileña" },
  { id: 5, name: "Generali" },
  { id: 6, name: "Zurich" },
  { id: 7, name: "Línea Directa" },
  { id: 8, name: "Reale Seguros" },
  { id: 9, name: "Ocaso" },
  { id: 10, name: "Helvetia" },
];

export const services = [
  { id: 1, name: "revision" },
  { id: 2, name: "aceite" },
  { id: 3, name: "frenos" },
  { id: 4, name: "neumaticos" },
  { id: 5, name: "bateria" },
  { id: 6, name: "averia" },
];

export const workshops = [
  {
    id: 1,
    name: "Taller AutoExpert Madrid",
    rating: 4.8,
    address: "Calle Alcalá 210, Madrid",
    responseTime: "15 min",
    phone: "+34 911 123 456",
    email: "contacto@autoexpert.es",
    services: ["revision", "aceite", "frenos", "neumaticos"],
    schedule: "L-V 08:00-19:00 | S 09:00-14:00",
    status: "Abierto",
    website: "https://www.autoexpert.es",
  },
  {
    id: 2,
    name: "MotorPlus Service",
    rating: 4.5,
    address: "Avenida de Andalucía 85, Sevilla",
    responseTime: "30 min",
    phone: "+34 954 222 333",
    email: "info@motorplus.es",
    services: ["aceite", "bateria", "averia"],
    schedule: "L-V 09:00-18:30",
    status: "Abierto",
    website: "https://www.motorplus.es",
  },
  {
    id: 3,
    name: "Box Rápido BCN",
    rating: 4.2,
    address: "Carrer d'Aragó 145, Barcelona",
    responseTime: "45 min",
    phone: "+34 934 456 789",
    email: "hola@boxrapido.com",
    services: ["revision", "frenos", "neumaticos", "averia"],
    schedule: "L-S 08:30-20:00",
    status: "Cerrado",
    website: "https://www.boxrapido.com",
  },
  {
    id: 4,
    name: "Taller Norte Premium",
    rating: 4.9,
    address: "Calle de Uría 32, Oviedo",
    responseTime: "10 min",
    phone: "+34 985 555 010",
    email: "premium@tallernorte.es",
    services: ["revision", "aceite", "frenos", "bateria", "averia"],
    schedule: "L-V 07:30-19:30",
    status: "Abierto",
    website: "https://www.tallernorte.es",
  },
];

const defaultOwnerUser1 = {
  name: "Carlos García",
  phone: "+34 600 111 222",
  email: "carlos.garcia@example.com",
};

export const vehicles = [
  {
    id: 1,
    userId: 1,
    brandId: 2, // BMW
    modelId: 4, // Serie 3
    insuranceId: 1,
    insuranceNumber: "MAP123456789",
    plate: "1234ABC",
    year: 2020,
    color: "Negro",
    status: "En Taller",
    mileage: 50000,
    ruta: null,
    owner: defaultOwnerUser1,
    taller: {
      name: "Taller AutoExpert Madrid",
      entryDate: "2026-04-28",
      estimatedFinish: "2026-05-05",
      exitDate: null,
      servicio: "aceite",
      serviceId: 2,
      repairStatus: "en_curso",
      performedByStaffId: 2,
      additionalServices: [],
    },
    facturas: {
      totalGlobalAnyo: 640,
      historial: [
        {
          name: "Cambio Aceite",
          total: 120,
          date: "2024-03-15",
        },
        {
          name: "Revisión Técnica",
          total: 200,
          date: "2025-03-15",
        },
        {
          name: "Cambio Pastillas de freno",
          total: 120,
          date: "2024-03-15",
        },
        {
          name: "Cambios llantas",
          total: 200,
          date: "2025-03-15",
        },
      ],
    },
    gastoGasolina: {
      totalUltimoMes: 100,
      historial: [
        {
          litros: 50,
          monto: 70,
          date: "2025-03-15",
        },
        {
          litros: 20,
          monto: 30,
          date: "2025-03-15",
        },
      ],
    },
  },
  {
    id: 2,
    userId: 1,
    brandId: 2, //BMW
    modelId: 3, // Serie 1
    insuranceId: 2,
    insuranceNumber: "ALL123456789",
    plate: "2234ABC",
    year: 2022,
    color: "Blanco",
    status: "Disponible",
    mileage: 20000,
    ruta: null,
    owner: defaultOwnerUser1,
    taller: null,
    facturas: {
      totalGlobalAnyo: 0,
      historial: [],
    },
    gastoGasolina: {
      totalUltimoMes: 0,
      historial: [],
    },
  },
  {
    id: 3,
    userId: 1,
    brandId: 2, //BMW
    modelId: 3, // Serie 1
    insuranceId: 2,
    insuranceNumber: "ALL123456789",
    plate: "2896ABC",
    year: 2022,
    color: "Blanco",
    status: "Disponible",
    mileage: 20000,
    ruta: null,
    owner: defaultOwnerUser1,
    taller: null,
    facturas: {
      totalGlobalAnyo: 0,
      historial: [],
    },
    gastoGasolina: {
      totalUltimoMes: 0,
      historial: [],
    },
  },
  {
    id: 4,
    userId: 1,
    brandId: 2,
    modelId: 4,
    insuranceId: 1,
    insuranceNumber: "MAP123",
    plate: "9922KLM",
    year: 2020,
    color: "Negro",
    status: "Disponible",
    mileage: 50000,
    ruta: null,
    owner: defaultOwnerUser1,
    taller: null,
    facturas: {
      totalGlobalAnyo: 0,
      historial: [],
    },
    gastoGasolina: {
      totalUltimoMes: 0,
      historial: [],
    },
  },
  {
    id: 5,
    userId: 1,
    brandId: 5,
    modelId: 9,
    insuranceId: 3,
    insuranceNumber: "AXA998877",
    plate: "4455XYZ",
    year: 2019,
    color: "Gris",
    status: "En Taller",
    mileage: 78000,
    ruta: null,
    owner: {
      name: "María López",
      phone: "+34 611 444 555",
      email: "maria.lopez@example.com",
    },
    taller: {
      name: "Taller AutoExpert Madrid",
      entryDate: "2026-05-01",
      estimatedFinish: "2026-05-10",
      exitDate: null,
      servicio: "revision",
      serviceId: 1,
      repairStatus: "en_espera",
      performedByStaffId: null,
      additionalServices: [],
    },
    facturas: { totalGlobalAnyo: 0, historial: [] },
    gastoGasolina: { totalUltimoMes: 0, historial: [] },
  },
  {
    id: 6,
    userId: 1,
    brandId: 4,
    modelId: 7,
    insuranceId: 4,
    insuranceNumber: "MMT112233",
    plate: "2211GOLF",
    year: 2021,
    color: "Azul",
    status: "Pendiente Recogida",
    mileage: 34000,
    ruta: null,
    owner: defaultOwnerUser1,
    taller: {
      name: "Taller AutoExpert Madrid",
      entryDate: "2026-04-20",
      estimatedFinish: "2026-05-01",
      exitDate: "2026-05-02",
      servicio: "frenos",
      serviceId: 3,
      repairStatus: "finalizada",
      performedByStaffId: 3,
      additionalServices: [{ serviceId: 4, name: "neumaticos" }],
    },
    facturas: { totalGlobalAnyo: 0, historial: [] },
    gastoGasolina: { totalUltimoMes: 0, historial: [] },
  },
  {
    id: 7,
    userId: 1,
    brandId: 11,
    modelId: 15,
    insuranceId: 2,
    insuranceNumber: "ALL556677",
    plate: "7788MAD",
    year: 2023,
    color: "Rojo",
    status: "En Taller",
    mileage: 12000,
    ruta: null,
    owner: {
      name: "Laura Sánchez",
      phone: "+34 622 333 888",
      email: "laura.sanchez@example.com",
    },
    taller: {
      name: "Taller AutoExpert Madrid",
      entryDate: "2026-04-30",
      estimatedFinish: "2026-05-03",
      exitDate: null,
      servicio: "averia",
      serviceId: 6,
      repairStatus: "en_curso",
      performedByStaffId: 1,
      additionalServices: [],
    },
    facturas: { totalGlobalAnyo: 0, historial: [] },
    gastoGasolina: { totalUltimoMes: 0, historial: [] },
  },
];

export const workshopUsers = [
  { id: 1, name: "Marta Admin", role: "admin" },
  { id: 2, name: "Diego Empleado", role: "empleado" },
];

/** Personal del taller (selects de orden / reparación) */
export const workshopStaff = [
  { id: 1, name: "Marta Admin", role: "admin" },
  { id: 2, name: "Diego Empleado", role: "empleado" },
  { id: 3, name: "Ana Mecánica", role: "empleado" },
];

export const workshopChatMessages = [
  { id: 1, author: "Recepcion", text: "Cliente de 1234ABC confirmado" },
  { id: 2, author: "Mecanica", text: "Pedido de frenos ya entregado" },
  { id: 3, author: "Admin", text: "Recordad cerrar ordenes del dia" },
];

export const workshopInvoices = [
  { id: 1, vehiclePlate: "1234ABC", total: 320, createdByRole: "admin" },
  { id: 2, vehiclePlate: "2234ABC", total: 145, createdByRole: "empleado" },
  { id: 3, vehiclePlate: "2896ABC", total: 580, createdByRole: "admin" },
];
